name: "AI Agent Evaluation"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login using Federated Credentials
        uses: azure/login@v2
        with:
          client-id: "ab36c882-c76f-40b3-a9ed-e213bfca0299"
          tenant-id: "62248d83-6539-4749-aeec-97936af356dc"
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Run Evaluation
        uses: microsoft/ai-agent-evals@v1-beta
        with:
          # Replace placeholders with values for your Azure AI Project
          # edit
          azure-aiproject-connection-string: "eastus.api.azureml.ms;33c24807-09a7-43fb-a742-915507254d7d;rg-ai-agent-evals;ai-project-gevydfxjhysra"
          deployment-name: "gpt-4o"
          agent-ids: "asst_PxtZxoO2kY5uSGsNzuo4uVph"
          data-path: ${{ github.workspace }}/evaluations/eval-dataset.csv
